nayafia/lemonade-stand

- README.md
Ryan created Node.js several months before joining Joyent as an employee. "Get hired by a company to work on project" seems like a more appropriate category for this case.
> Move Ryan Dahl and Joyent case to different category

- README.md
In some contexts, especially when rendered on mobile, the GitHub Markdown rendering engine seems less lenient wth the formatting syntax.
Having spaces after `##` title markers and empty lines after titles fixes that and ensure it's rendered correctly in every contexts.
> Fix Markdown rendering

- README.md
Segment just announced an open source fellowship that looks similar to Stripe's.
Adding to the list, as there are such few examples of corporate grants :tada:
> Add Segment Open Fellowship to grant examples

- README.md
ChatSecure started experimenting with a donation button, to find independence from grant funding:
https://chatsecure.org/blog/sustainable-open-source-starts-with-you/
Adding them as an example.
> Add ChatSecure to donation examples

- README.md
Caddy recently announced a commercial license offering. mholt did a thorough retrospective that I think is useful for others to learn from.
I've listed Caddy under "open core" because its source code is Apache 2.0 no matter what, but its binaries require  a commercial license if you are a company. I think that's the right category!
> Add Caddy case study

- README.md
Adds Gitcoin to the list of projects that support bounties -- We recently announced support for several pilot projects like Metamask and Truffle, and have thousands of dollars of open issues on the system.
> Adds Gitcoin

- README.md
Adding [License Zero](https://medium.com/licensezero/the-license-zero-manifesto-fecb7aaf4c0a) as a type of freemium/"shared source" license, which has come up multiple times in conversations these days.
> Add License Zero

- README.md
Adds the [Varnish Moral License](http://phk.freebsd.dk/VML/), with the blessing of Poul-Henning Kamp https://twitter.com/bsdphk/status/935148193733644288
This is a funny one I came across awhile ago, but never added (see Twitter thread re: why). It's called a "license", but really it's a company sponsorship masquerading as a contract/invoice. Definitely worth a look!
> Add Varnish Moral License

- README.md
I find this is one of the cons I refer to the most when discussing freemium licenses: in part, open source is popular because it costs nothing. Charging for use could suppress user adoption.
> Add note about adoption to freemium licenses

- README.md
Hi,
Rather than get into discussing any of the details, I just did edits throughout while reading. Several of my changes are plainly appropriate (Gratipay is gone for example). Others you may not agree with (though I don't think any ought to be controversial) but I think all of them are improvements. I'll consider updating the PR if you have specific concerns but are willing to consider these changes otherwise.
* Open Collective is not a 501(c)(3) although they function as a legal entity for projects in other ways. The previous version implied they were 501(c)(3)
* made links default to HTTPS
* did some edits to the opening wording while I was at it, more succinct and to the point.
* replaced Gratipay with Liberapay (Gratipay is gone now, closing)
* Freemium was described confusingly. …
> various edits throughout

- README.md
Upon revisiting this section, I decided the wording felt too complicated, and somehow we'd lost a couple useful parts (like permissive licenses) in the last revision. Sorry! Cleaned it up a bit.
> Simplify dual licensing section

- README.md
Found this example [in the wild](https://twitter.com/desandro/status/954435191782694913). @desandro says:
> Hi! This is how I’ve run @metafizzyco for past 7 years. I got lucky and was able to switch to full-time OSS after 3 years
The docs around Metafizzy's commercial licenses are pretty comprehensive, so recommend checking it out for anyone who's interested in a dual licensing model.
> Add Metafizzy to dual license section

- README.md
[Flattr](https://flattr.com/creators) isn’t quite one-time nor recurring, but somewhere in between. Developers can link their GitHub accounts and domains to Flattr, and receive a share of Flattr users’ monthly contribution based on whether people visited their GitHub project pages and domains.
> Add Flattr to recurring crowdfunding services list

- README.md
Ungit switched back from Faircode to MIT License. See https://github.com/FredrikNoren/ungit/issues/997.
I thought, this is worth to be still noticed as "case study" and thus, I changed the link text and the link.
> Update information on Ungit

- README.md
I came across this conference talk from another repo (https://github.com/nayafia/awesome-maintainers/pull/18).
It's super good! Only 15 min long and very practical insights from Phusion Passenger's maintainers, `@FooBarWidget` and `@prototype`. Recommend checking it out if you're trying to monetize an open source project.
> Add Phusion Passenger conference talk

- README.md
Signal recently announced the creation of a $50M foundation to support their ongoing development, thanks to Brian Acton (cofounder of WhatsApp).
> We’ve always wanted to do much more, and our limitations have often been challenging. Over the lifetime of the project, there have only been an average of 2.3 full-time software developers, and the entire Signal team has never been more than 7 people.
https://signal.org/blog/signal-foundation/
> Add Signal Foundation

- README.md
Came across this example in a [Medium post](https://medium.com/@dhsue/an-analysis-of-monero-governance-3f8bef770b29). Monero's community members can request funding to work on the project, using a public proposal system.
[Here's an example](https://getmonero.org/forum-funding-system/proposals/documentation-cleanup.html) of someone who was funded to improve Monero's documentation.
h/t [Derek Hsue](https://twitter.com/derek_hsue) for flagging!
> Add Monero's funding proposal system

- README.md
Ok after https://github.com/nayafia/lemonade-stand/pull/82 I couldn't believe there wasn't a `Paid Support` section, so I added one 😅
I'm really interested in the idea of charging for support, it seems like there's a lot of potential there, since managing support/issues seems to be what bogs maintainers down the most.
It's also interesting to me bc you can do it on so many levels: from charging for access to your Slack channel, to, well, Red Hat.
I added a few examples off the top of my head, but I'm sure there are more. Feel free to suggest edits!
> Add a Paid Support section

- README.md
The Handshake project announced yesterday that it raised $10.2M from VCs and angels, all of which will be distributed to free and open source developers: https://handshake.org/
Project recipients include GNOME, Babel, Ruby Together, FreeBSD. Here's GNOME's announcement about their $400K grant: https://twitter.com/gnome/status/1025076048352948224
They're also distributing 70% of their coin supply to FOSS via "faucet", which developers can apply for on the website.
I was pretty psyched to see this. It'll be an interesting experiment to follow!
> Add Handshake community grant program

- README.md
Lots of chatter about Redis's decision to move some of its code to a new Commons Clause license, which restricts commercial use.
As Commons Clause joins the ranks of similar not-open-source licenses (Fair Source, License Zero, etc) I took the opportunity to revise and rename this section. Still don't have a great name for these (I went with `restricted license`), but even I wasn't sure what "shared source" was upon revisiting this section.
> Add Redis Commons Clause

- README.md
"Dual license" normally means something different, namely releasing one project under two or more licenses simultaneously, often for broader compatibility with other Open Source licenses. For instance, the Rust project is dual-licensed under MIT and Apache 2.0. "Dual license" doesn't normally describe the business model of selling *separate* alternative non-copyleft licenses.
Expand the text a bit, to clarify what kinds of companies might purchase such exceptions (not *all* companies prefer non-copyleft), and to allow for other legal structures in doing so.
> Rename "Dual license" to "Selling exceptions" and expand

- README.md
`josephjacks` [recently announced](https://twitter.com/asynchio/status/1046792188850397184) the formation of a venture fund, [OSS Capital](https://oss.capital/), focused exclusively on funding commercial open source projects:
> The world's first and only commercial OSS-founder-backed and founded exclusively focused on investing in + supporting commercial OSS founders
> Add OSS Capital

- README.md
This is an interesting example of a project (Grin) that's [crowdfunding their development](http://grin-tech.org/funding.html) with a recurring "general fund". 
> To keep Grin open and free from controlling influences, the project will attempt to rely 100% on community donations for its funding needs.
Also recommend checking out how they ran a [campaign for Yeastplume](http://grin-tech.org/yeastplume.html), a developer on the project.
They don't have a foundation, instead using multisig wallets + fund developers directly. I've written a few relevant pieces about this [1][2], so cool to find another example in the wild.
[1] Decentralized funding? An analysis of three programs: https://nadiaeghbal.com/grant-programs
[2] Governance without foundations: https://nadiaeghbal.com/foundations
> Add Grin General Fund - community crowdfunding

- README.md
This is pretty interesting: https://inkscape.org/support-us/funded-development/
I have no idea how well it works in practice, but they seem to strike a good balance between centralized and decentralized management. Money goes towards funding development work that nobody wants to do *as a volunteer*, and only trusted contributors (those listed in the AUTHORS file) can apply to work on them. Kind of like bounties 2.0.
> This is so that any proposed projects that are fun or easy get done by volunteers, and money can be focused on harder unsexy work
/cc @owocki @coderberry in case it's of interest, made me think of Gitcoin!
Related reading:
- Blog post I wrote last fall about [decentralized funding programs](https://nadiaeghbal.com/grant-programs). Always cool to see how bigger projects …
> Add Inkscape's "funded development" system

- README.md
Hadn't seen this before! [Markdown Monster](https://markdownmonster.west-wind.com/) is source available (meaning you can view and download the source code), but you are required to purchase a license for continued use.
However, users who make valuable contributions back to the project [qualify for a free license](https://markdownmonster.west-wind.com/download.aspx#Contribute):
> Contributors that provide valuable feedback with quality bug reports or enhancement requests, help out with code via Pull Requests, help promote Markdown Monster, or support Markdown Monster in any other significant way are all eligible for a free license.
I have no idea how this all holds up legally, but thought it was an elegant approach to aligning incentives. h/t @sonyamann for [finding this …
> Add Markdown Monster

- README.md
Onimvim 2 is a pre-alpha project running [a bunch of interesting experiments](https://github.com/onivim/oni2#license):
* Free for non-commercial and educational use
* Commercial license is pay-what-you-want, with the minimum pre-order price increasing as they get closer to shipping an MVP
* Anyone who financially sponsors the project (via BountySource, Patreon, PayPal, or OpenCollective) gets a free lifetime license
* Commits are dual-licensed with MIT after 18 months from commit's date to master
> Add Onivim 2: tiered license pricing + dual license

- README.md
From their [blog post](https://formidable.com/blog/2019/sauce-program/):
> For the last nine months we’ve experimented with paying our employees for any open source contributions to any project they do on their free time, no strings attached. [...]
> We pay our employees $20/hr for contributions to OSS and tech communities, whether it’s a third-party library we use in our work like React, Next.js, or styled-components; one of our own OSS projects like Spectacle or Urql; or even a personal hack project purely for fun and learning, as long as it’s released under an OSI license. Contributions can be code, documentation, design work, pull request reviews, issue triage, community management, or really anything that the individual thinks counts as a contribution [...]
> During the trial period, …
> Add Formidable's Sauce program for employees

- README.md
Feross recently ran an experiment where he displayed ads to users who installed StandardJS. Adding his [recap](https://feross.org/funding-experiment-recap/) of the experiment here.
It also reminded me of this thing that happened with Kite/Minimap a few years ago, so I added that to the list too. (It's my personal summary of it at the time, which I feel a little weird pointing to, but I'm trying not to link directly to controversial GitHub issues -- even if locked -- to avoid encouraging pile-ons. Happy to change this link to a different summary if someone finds one.)
> Add examples to advertising section

- README.md
This is a [great post](https://calebporzio.com/i-just-hit-dollar-100000yr-on-github-sponsors-heres-how-i-did-it) about how Caleb Porzio is making $100K in recurring sponsorships on GitHub Sponsors by experimenting with different value propositions.
> Add Caleb Porzio making $100K on GitHub Sponsors

- README.md
- https://resources.github.com/github-secure-open-source-fund/
- https://floss.fund/
@nayafia please tell me if it's better to link to one of the FLOSS/fund [update posts](https://floss.fund/blog/update-2025-may/) instead of the https://floss.fund homepage
> Add GitHub Secure Open Source Fund and FLOSS/Fund to Grants section
