nayafia/lemonade-stand

- README.md
I felt this model is different enough it deserves it's own section.
> Added Managed / Hosted Services

- README.md
Sidekiq is not a SaaS but rather an open core product, [Iron.io](https://www.iron.io/) is a job processing SaaS.
> Move Sidekiq to Open Core

- README.md
Adding You Don't Know JS by @getify in Books and Merchandise Case Studies.
> Add You Don't Know JS in Books Case Studies

- README.md
> add Chinese characters in translation link to make it stands out

- README.md
legal entity only needed for charitable donations - personal donations (e.g. via paypal) can be accepted by anyone. Collective donations are really a third type.
> clarifying donation

- README.md
> Gitlab => GitLab, change link to HTTPS

- README.md
I published a recap on Kickstarter
> Update RESTful WP-CLI link

- README.md
I recognize that freemium licenses (ex. Fair Source, BSL) are not actually open source, and I've made that explicit in the description. However, it seems they are trying to answer the same question outlined in this guide, so it seems that anybody interested in this topic should know that these types of licenses exist.
> add freemium licenses to list

- README.md
Welp. Can't not include a $450K+ fundraise for an open source project on this list. :)
> add Font Awesome to crowdfunding case studies

- README.md
Added a few more examples I've heard about to the Bounty section.
> Add bounty program examples

- README.md
> Add Japanese link

- README.md
Great example of a recurring crowdfunding campaign on Patreon.
> Add Vue.js

- README.md
@librariesio published their successful grant applications online, which I thought would be useful for anyone else who's looking to write a similar grant. Adding to "Grants" section.
> Add Libraries.io grant applications

- README.md
GnuPG is raising 15K euro/month. I really like their crowdfunding page as inspiration: 
- Video
- Stories
- How your money will be used
- Testimonials
- Team bios
> Add GnuPG as recurring funding example

- README.md
https://clojuriststogether.org
https://clojuriststogether.org/news/introducing-clojurists-together/
> Add Clojurists Together project

- README.md
OSS paid in bounties / cryptocurrency delegated by smart contracts in ethereum - Pledged 1M USD recently to OSS projects in general.
> add Status Open Bounty

- README.md
> Add Qt example for dual license

- README.md
Another interesting crowdfunding example. People can submit proposals for a small fee, which are voted on by a whitelisted subset of the community. Proposals with >10% voter turnout and enough yes's get paid out. More info [here](https://dashpay.atlassian.net/wiki/spaces/DOC/pages/19169430/Using+Decentralized+Governance+Proposals+Voting+and+Budgets).
These types of systems almost warrant their own category (there are definitely pros and cons to using a voting system!), but I'm not quite ready to break it out yet. 😉
Perhaps noteworthy: many of these proposals are about community and education, not code.
> Add Dash as crowdfunding example

- README.md
Saw https://gdalbarn.com/ on Twitter via `pramsey`. They're raising $125K to make some upgrades:
> Coordinate systems in GDAL, PROJ, and libgeotiff are missing modern capabilities and need a thorough refactoring
I like how thorough the documentation is here (including a sponsor leaderboard!), so adding it as an example to the `Crowdfunding (one-time)` list.
> Add GDAL as crowdfunding example

- README.md
* Use datproject.org for Dat url
* Add a blog post about our grants
> Update Dat link and add blog post about funding history

- README.md
Add IssueHunt that is an issue based bounty platform for OSS.
https://issuehunt.io
> Add IssueHunt

- README.md
Case studies need better organization and descriptions. There are a million things I could do here that I'm not atm, but at least they are now alphabetized.
> Alphabetize case study lists

- README.md
PR for #100 
Thanks for this repo @nayafia
> link to spanish translation #100

- README.md
Sentry is offering a $10K stipend for people contributing to open source projects: https://blog.sentry.io/2019/01/29/apply-sentry-open-source-grant
Also tweaked the grant category description here a bit.
> Add Sentry's Open Source Grant

- README.md
ESLint just started an OpenCollective for their work. I thought their blog post was a nice writeup that includes how the money will be spent: https://eslint.org/blog/2019/02/funding-eslint-future
> Add ESLint

- README.md
CZI just announced a new grant program: $50-250K grants for scientific open source software 🎉 Details here: https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/
> Add Chan-Zuckerberg Initiative: $50-250K grants

- README.md
> Fix very minor typos

- README.md
Just fixing the link that is currently broken
> Fix broken link to Caddy

- README.md
Adds @calebporzio's Sponsorware idea
> Add Sponsorware

- README.md
link grant list
link crowdfunding list
> add ralphtheninja/open-funding

- README.md
https://github.com/bountysource/core/issues/1586
> Bountysource is dead
